---
openapi: "3.0.1"
info:
  title: "Dictionary service REST API"
  description: "If you need to update your dictionary, you're at the right place"
  version: "yolo"
servers:
  - url: "http://localhost:8080/"
paths:
  /pony:
    get:
      tags:
        - "pony-controller"
      summary: "get"
      operationId: "getUsingGET"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pony"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
    post:
      tags:
        - "pony-controller"
      summary: "post"
      operationId: "postUsingPOST"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pony"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pony"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
components:
  schemas:
    Pony:
      discriminator:
        propertyName: ponyType
        mapping:
          pegasi: "#/components/schemas/Pegasi"
          unicorn: "#/components/schemas/Unicorn"
      type: "object"
      properties:
        name:
          type: "string"
        ponyType:
          type: string

    Pegasi:
      allOf:
        - $ref: "#/components/schemas/Pony"
        - type: "object"
          properties:
            wingsColors:
              type: "string"
              default: "RED"
    Unicorn:
      allOf:
        - $ref: "#/components/schemas/Pony"
        - type: "object"
          properties:
            cornSize:
              type: "integer"
              default: 10